[build]
  base = "Ui/portfolio"
  command = "npm run build:prod"
  publish = "dist/portfolio/browser"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4200
  publish = "dist/portfolio/browser" 