services:
  - type: web
    name: portfolio-angular
    env: static
    buildCommand: cd Ui/portfolio && npm install && npm run build:prod
    staticPublishPath: ./Ui/portfolio/dist/portfolio/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20 