[build]
  base = "portfolio"
  publish = "dist/portfolio/browser"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 