services:
  - type: web
    name: portfolio-backend
    env: java
    plan: free
    buildCommand: cd portfolio-microservice && ./mvnw clean package -DskipTests
    startCommand: cd portfolio-microservice && java -jar target/portfolio-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false 