[build]
  base = "."
  publish = "portfolio/dist/portfolio/browser"
  command = "cd portfolio && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 