services:
  - type: web
    name: portfolio-angular
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/portfolio/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20 